wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716360401
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.17.0
      8:
      - 5
      13: darwin-arm64
